In [3]:
#import torch library,which helps to build and train the model,and handle torch operations
!pip install torch
import torch
import numpy as np

  Using cached torch-2.5.1-cp311-cp311-win_amd64.whl.metadata (28 kB)
Using cached torch-2.5.1-cp311-cp311-win_amd64.whl (203.1 MB)
   ---------------------------------------- 0.0/203.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/203.1 MB 1.6 MB/s eta 0:02:07
   ---------------------------------------- 0.1/203.1 MB 1.7 MB/s eta 0:02:01
   ---------------------------------------- 0.2/203.1 MB 1.7 MB/s eta 0:01:58
   ---------------------------------------- 0.3/203.1 MB 1.6 MB/s eta 0:02:07
   ---------------------------------------- 0.4/203.1 MB 1.9 MB/s eta 0:01:50
   ---------------------------------------- 0.6/203.1 MB 2.2 MB/s eta 0:01:32
   ---------------------------------------- 0.7/203.1 MB 2.3 MB/s eta 0:01:29
   ---------------------------------------- 0.8/203.1 MB 2.6 MB/s eta 0:01:20
   ---------------------------------------- 1.0/203.1 MB 2.6 MB/s eta 0:01:18
   ---------------------------------------- 1.3/203.1 MB 2.9 MB/s eta 0:01:11
   --------------

In [4]:
data=[
    [1,2],
    [3,4]
]

In [8]:
np_array=np.array(data)
x=torch.from_numpy(np_array)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
x_ones=torch.ones_like(x)
print("One tensor with the same shape of X is:\n",x_ones)

One tensor with the same shape of X is:
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [10]:
x_rand=torch.rand_like(x,dtype=torch.float)
print("Random tensor with the same shape of X is:\n",x_rand)

Random tensor with the same shape of X is:
 tensor([[0.4959, 0.2988],
        [0.7217, 0.5913]])


In [11]:
shape=(2,3)

In [12]:
random_tensor=torch.rand(shape)
print("Random tensor of above shape is:\n",random_tensor)

ones_tensor=torch.ones(shape)
print("One tensor of above shape is:\n",ones_tensor)

zeros_tensor = torch.zeros(shape)  
print("Zeros tensor of above shape is:\n",zeros_tensor)

Random tensor of above shape is:
 tensor([[0.2645, 0.9549, 0.3234],
        [0.1854, 0.4398, 0.0412]])
One tensor of above shape is:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros tensor of above shape is:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [26]:
#checks if a CUDA-capable GPU is available on your system.
if torch.cuda.is_available():
#transfers the tensor from the CPU to the GPU
    tensor=tensor.to('cuda')  
    print("Device tensor stored in:",tensor.device)

In [27]:
#indexing,slicing
tensor1=torch.ones(4,4)
print(tensor1)
tensor2=torch.zeros(4,4)
print(tensor2)
tensor3 = torch.cat([tensor1, tensor2])  
print(tensor3) 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [23]:
tensor1.mul(tensor2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#transpose 
tensor1.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])